### ISSUE TITLE
Getting "Error: Unsupported Terraform Core version"

### ISSUE THREAD

**Issue by MarkofTheKanes** [hashicorp/learn-terraform-variables#13]
Hi Folks,

I'm doing the Terraform tutorials and have reached the Variables tutorial @ [https://developer.hashicorp.com/terraform/tutorials/cli/variables](https://developer.hashicorp.com/terraform/tutorials/cli/variables)). I cloned the repo @ https://github.com/hashicorp/learn-terraform-variables.git but the terraform init fails with 

Error: Unsupported Terraform Core version
│ 
│   on terraform.tf line 20, in terraform:
│   20:   required_version = "~> 1.2.0"
│ 
│ This configuration does not support Terraform version 1.7.3. To
│ proceed, either choose another supported Terraform version or update
│ this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or
│ unexpected behavior.

I changed the required_version to 1.7.0 (from 1.2.0) in the main.tf file and it worked. Was I correct in doing this i.e. will it have unknown consequences? The apply also seemed to work but I'd like to be sure.

Here is the full results from the init...

Initializing the backend...
Initializing modules...
Downloading registry.terraform.io/terraform-aws-modules/security-group/aws 4.17.0 for app_security_group...
- app_security_group in .terraform/modules/app_security_group/modules/web
- app_security_group.sg in .terraform/modules/app_security_group
- ec2_instances in modules/aws-instance
Downloading registry.terraform.io/terraform-aws-modules/elb/aws 4.0.1 for elb_http...
- elb_http in .terraform/modules/elb_http
- elb_http.elb in .terraform/modules/elb_http/modules/elb
- elb_http.elb_attachment in .terraform/modules/elb_http/modules/elb_attachment
Downloading registry.terraform.io/terraform-aws-modules/security-group/aws 4.17.0 for lb_security_group...
- lb_security_group in .terraform/modules/lb_security_group/modules/web
- lb_security_group.sg in .terraform/modules/lb_security_group
Downloading registry.terraform.io/terraform-aws-modules/vpc/aws 3.19.0 for vpc...
- vpc in .terraform/modules/vpc
╷
│ Error: Unsupported Terraform Core version
│ 
│   on terraform.tf line 20, in terraform:
│   20:   required_version = "~> 1.2.0"
│ 
│ This configuration does not support Terraform version 1.7.3. To
│ proceed, either choose another supported Terraform version or update
│ this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or
│ unexpected behavior.

**Comment by BradleyYeo** [comment]
I just submitted a pull request to fix this, you can consider using tfenv to switch terraform versions to what is being used in the provider block to ensure compatibility :)

**Comment by MarkofTheKanes** [comment]
Thanks Bradley and will do.

**Comment by MageshSrinivasulu** [comment]
@BradleyYeo Can you please share the pull request details facing a similar issue

**Comment by robin-norwood** [comment]
Apologies for the delay, this issue [has been fixed](https://github.com/hashicorp/learn-terraform-variables/pull/18)!
